name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.5
  - seaborn=0.11.2
  - pandas=1.3.5
  - pip=21.3.1
  - pyarrow=6.0.1
  - matplotlib=3.5.1
  - wandb=0.12.9
  - pandas-profiling=3.1.0
  - scikit-learn=1.0.2
  - pip:
      - dataprep==0.4.1
      